--accountmodule
GRANT SELECT, INSERT, UPDATE ON ACCOUNTS TO accountmodule;
GRANT SELECT, INSERT ON PERSONAL_DATA TO accountmodule;
GRANT INSERT ON ACCOUNT_ROLE TO accountmodule;
GRANT SELECT, INSERT, UPDATE, DELETE ON EMAIL_VERIFICATION_TOKENS TO accountmodule;
GRANT SELECT, INSERT, UPDATE, DELETE ON RESET_PASSWORD_TOKENS TO accountmodule;
GRANT SELECT, INSERT, UPDATE ON ACCOUNT_ROLE TO accountmodule;
GRANT SELECT, INSERT ON ADMIN_DATA TO accountmodule;
GRANT SELECT, INSERT ON CLIENT_DATA TO accountmodule;
GRANT SELECT, INSERT ON LANDLORD_DATA TO accountmodule;
-- authenticationmodule
GRANT SELECT ON ACCOUNTS TO authenticationmodule;
GRANT SELECT ON PERSONAL_DATA TO authenticationmodule;
GRANT SELECT ON ACCOUNT_ROLE TO authenticationmodule;
GRANT SELECT ON CLIENT_DATA TO authenticationmodule;
GRANT SELECT ON LANDLORD_DATA TO authenticationmodule;
GRANT SELECT ON ADMIN_DATA TO authenticationmodule;