GRANT SELECT, INSERT, UPDATE ON ACCOUNTS TO accountmodule;
GRANT SELECT, INSERT ON PERSONAL_DATA TO accountmodule;
GRANT INSERT ON ACCOUNT_ROLE TO accountmodule;
GRANT INSERT ON CLIENT_DATA TO accountmodule;
GRANT SELECT, INSERT, UPDATE, DELETE ON EMAIL_VERIFICATION_TOKENS TO accountmodule;
GRANT SELECT, INSERT, UPDATE, DELETE ON RESET_PASSWORD_TOKENS TO accountmodule;