GRANT INSERT ON ACCOUNTS TO accountmodule;
GRANT INSERT ON PERSONAL_DATA TO accountmodule;
GRANT INSERT ON ACCOUNT_ROLE TO accountmodule;
GRANT INSERT ON CLIENT_DATA TO accountmodule;
GRANT INSERT ON EMAIL_VERIFICATION_TOKENS TO accountmodule;